#!/bin/sh -e

HOST=$1
PORT=$2

echo "Graphite Host ${HOST}:${PORT}"

sed -i -e "s/graphite_host/${HOST}/g" /diamond/handlers/GraphiteHandler.conf 
sed -i -e "s/graphite_port/${PORT}/g" /diamond/handlers/GraphiteHandler.conf 

diamond -c /diamond/diamond.conf -f -l
